"""Add cascade delete to imagen_evento_salud foreign key

Revision ID: add_cascade_delete_imagen_evento
Revises: e2f3a4b5c6d7
Create Date: 2026-03-02 02:20:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_cascade_delete_imagen_evento'
down_revision = 'e2f3a4b5c6d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # First, drop the existing foreign key constraint
    op.drop_constraint('fk_imagen_evento_salud_evento_salud_id_evento_salud', 'imagen_evento_salud', type_='foreignkey')
    
    # Then add it back with CASCADE delete
    op.create_foreign_key(
        'fk_imagen_evento_salud_evento_salud_id_evento_salud', 
        'imagen_evento_salud', 
        'evento_salud', 
        ['evento_salud_id'], 
        ['id'], 
        ondelete='CASCADE'
    )
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the cascade delete constraint
    op.drop_constraint('fk_imagen_evento_salud_evento_salud_id_evento_salud', 'imagen_evento_salud', type_='foreignkey')
    
    # Add back the original constraint without cascade
    op.create_foreign_key(
        'fk_imagen_evento_salud_evento_salud_id_evento_salud', 
        'imagen_evento_salud', 
        'evento_salud', 
        ['evento_salud_id'], 
        ['id']
    )
    
    # ### end Alembic commands ###
