"""Add Camara model

Revision ID: d3c01eb04d66
Revises: 
Create Date: 2026-02-02 17:41:08.040986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3c01eb04d66'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payroll_runs')
    op.drop_table('payroll_items')
    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.alter_column('peso_promedio_crias',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('produccion_diaria',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('peso_promedio_crias_nacimiento',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('promedio_crias_por_camada',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('idx_animal_ubicacion'))
        batch_op.create_foreign_key('fk_animal_ubicacion_id_ubicacion', 'ubicacion', ['ubicacion_id'], ['id'])
        batch_op.drop_column('peso_promedio_camada')
        batch_op.drop_column('peso_promedio_lechones')
        batch_op.drop_column('lechones_nacidos_vivos')
        batch_op.drop_column('promedio_lechones_por_camada')
        batch_op.drop_column('lechones_nacidos_muertos')
        batch_op.drop_column('numero_camada')

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('nacionalidad',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
        batch_op.alter_column('referencia_personal',
               existing_type=sa.TEXT(),
               type_=sa.String(length=200),
               existing_nullable=True)
        batch_op.alter_column('referencia_file',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('alergico_medicamento',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
        batch_op.alter_column('foto_empleado',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.alter_column('foto_cedula',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    with op.batch_alter_table('potrero', schema=None) as batch_op:
        batch_op.alter_column('funcion',
               existing_type=sa.VARCHAR(length=200),
               type_=sa.String(length=100),
               existing_nullable=False)

    with op.batch_alter_table('ubicacion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_ubicacion_finca'))
        batch_op.drop_index(batch_op.f('idx_ubicacion_tipo'))

    # Create camara table
    op.create_table('camara',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('finca_id', sa.Integer(), nullable=False),
    sa.Column('posicion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['finca_id'], ['finca.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ubicacion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_ubicacion_tipo'), ['tipo_ubicacion'], unique=False)
        batch_op.create_index(batch_op.f('idx_ubicacion_finca'), ['finca_id'], unique=False)

    with op.batch_alter_table('potrero', schema=None) as batch_op:
        batch_op.alter_column('funcion',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=200),
               existing_nullable=False)

    with op.batch_alter_table('empleado', schema=None) as batch_op:
        batch_op.alter_column('foto_cedula',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('foto_empleado',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('alergico_medicamento',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('referencia_file',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('referencia_personal',
               existing_type=sa.String(length=200),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('nacionalidad',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('cargo',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('animal', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_camada', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('lechones_nacidos_muertos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('promedio_lechones_por_camada', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('lechones_nacidos_vivos', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('peso_promedio_lechones', sa.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('peso_promedio_camada', sa.FLOAT(), nullable=True))
        batch_op.drop_constraint('fk_animal_ubicacion_id_ubicacion', type_='foreignkey')
        batch_op.create_index(batch_op.f('idx_animal_ubicacion'), ['ubicacion_id'], unique=False)
        batch_op.alter_column('promedio_crias_por_camada',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('peso_promedio_crias_nacimiento',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('produccion_diaria',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('peso_promedio_crias',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)

    op.create_table('payroll_items',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('payroll_run_id', sa.INTEGER(), nullable=False),
    sa.Column('empleado_id', sa.INTEGER(), nullable=False),
    sa.Column('salario_base', sa.FLOAT(), nullable=False),
    sa.Column('bonificaciones', sa.FLOAT(), nullable=True),
    sa.Column('deducciones', sa.FLOAT(), nullable=True),
    sa.Column('neto', sa.FLOAT(), nullable=True),
    sa.Column('fecha_pago', sa.DATE(), nullable=True),
    sa.Column('notas', sa.TEXT(), nullable=True),
    sa.Column('creado_en', sa.DATETIME(), nullable=True),
    sa.Column('tipo_pago', sa.VARCHAR(length=20), server_default=sa.text("'nomina'"), nullable=True),
    sa.Column('estado_pago', sa.VARCHAR(length=20), server_default=sa.text("'pendiente'"), nullable=True),
    sa.Column('metodo_pago', sa.VARCHAR(length=20), nullable=True),
    sa.Column('comprobante_url', sa.VARCHAR(length=255), nullable=True),
    sa.Column('tasa_cambio', sa.FLOAT(), nullable=True),
    sa.Column('monto_original', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['empleado_id'], ['empleado.id'], ),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=128), nullable=True),
    sa.Column('periodo_inicio', sa.DATE(), nullable=False),
    sa.Column('periodo_fin', sa.DATE(), nullable=False),
    sa.Column('estado', sa.VARCHAR(length=20), nullable=True),
    sa.Column('creado_por', sa.Integer(), nullable=True),
    sa.Column('fecha_creacion', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('camara')
    # ### end Alembic commands ###
